### ISSUE TITLE
Activity tracking: ability to remove an event

### ISSUE THREAD

**Issue by sandrock** [sandrock/mynatime#19]
When using activity tracking, the user creates activity change events (start this, stop that, start this at time...).

Somethings, the user may execute an incorrect command and create a wrong event. Code these commands:

- [ ] `m act del evt <event-id>+`
  -   deletes the event
- [ ] `m act del evt all`
  -   deletes all the event

And code these changes:

- [ ] events should have a unique id
- [ ] existing events (in the profile file) should gain a unique id
- [ ] `m act` displays an ID for each event
